pipeline {
    agent any
	stages {

    stage('Checkout') {
        steps {
            checkout scm
        }
    }

    stage('Check Workspace') {
        steps {
            sh 'pwd'
            sh 'ls -la'
            sh 'find . -maxdepth 2 -type d'
        }
    }

        stage('Build Vote Image') {
            steps {
                sh 'docker build -t sanidhyapal/vote:latest vote'
            }
        }

        stage('Build Worker Image') {
            steps {
                sh 'docker build -t sanidhyapal/worker:latest worker'
            }
        }

        stage('Build Result Image') {
            steps {
                sh 'docker build -t sanidhyapal/result:latest result'
            }
        }
    }
}
